# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babyusername', models.CharField(default='', max_length=20, verbose_name='产品中文名')),
                ('babyname', models.CharField(max_length=20, verbose_name='产品类别')),
                ('clientname', models.CharField(max_length=10, verbose_name='收件人')),
                ('mobile', models.CharField(max_length=15, verbose_name='手机号')),
                ('price', models.FloatField(max_length=10, verbose_name='金额')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(default='', max_length=30, verbose_name='地址')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('remark', models.CharField(default='', max_length=50, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '订单编号',
                'verbose_name_plural': '订单编号',
            },
        ),
    ]
