# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashorders',
            name='clientname',
            field=models.CharField(max_length=20, verbose_name='收件人'),
        ),
    ]
