# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30, verbose_name='地址')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
            },
        ),
        migrations.CreateModel(
            name='orderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babyusername', models.CharField(default='', max_length=20, verbose_name='产品中文名')),
                ('babyname', models.CharField(max_length=20, verbose_name='产品类别')),
                ('clientname', models.CharField(max_length=20, verbose_name='收件人')),
                ('mobile', models.CharField(max_length=15, verbose_name='手机号')),
                ('price', models.FloatField(max_length=10, verbose_name='金额')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(default='', max_length=30, verbose_name='地址')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('remark', models.CharField(default='', max_length=50, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '订单用户',
                'verbose_name_plural': '订单用户',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.IntegerField(verbose_name='taobaoid')),
                ('projectName', models.CharField(default='', max_length=60, verbose_name='babyname产品名称')),
                ('projectIndexImage', models.CharField(default='', max_length=9999, verbose_name='上滚主图片地址')),
                ('projectDescribe', models.CharField(max_length=9999, verbose_name='projectsDescribeHTML')),
                ('projectPrice', models.FloatField(default=998, verbose_name='默认价格')),
                ('sellername', models.CharField(max_length=30, verbose_name='sellname商家账户')),
            ],
            options={
                'verbose_name': ('产品详情',),
                'verbose_name_plural': ('产品详情',),
            },
        ),
        migrations.CreateModel(
            name='projectColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectcolorId', models.CharField(max_length=20)),
                ('projectcolorname', models.CharField(max_length=60, verbose_name='babyname')),
                ('projectcolortaiwanname', models.CharField(max_length=60, null=True, verbose_name='babyname')),
            ],
            options={
                'verbose_name': ('产品颜色',),
                'verbose_name_plural': ('产品颜色',),
            },
        ),
        migrations.CreateModel(
            name='projectColorImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectColorImages', models.CharField(max_length=9999, null=True, verbose_name='babyname')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
                ('projectcolorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projectColor')),
            ],
            options={
                'verbose_name': ('顏色圖片',),
                'verbose_name_plural': ('顏色圖片',),
            },
        ),
        migrations.CreateModel(
            name='projectSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectSizeId', models.IntegerField(verbose_name='编号')),
                ('projectSizename', models.CharField(max_length=60, verbose_name='尺码名')),
            ],
            options={
                'verbose_name': ('产品尺码表',),
                'verbose_name_plural': ('产品尺码表',),
            },
        ),
        migrations.CreateModel(
            name='projectSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectSkuPrice', models.FloatField(verbose_name='产品价格')),
                ('projectColorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projectColor')),
                ('projectSizeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projectSize')),
                ('projectSkuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
            options={
                'verbose_name': ('sku价格',),
                'verbose_name_plural': ('sku价格',),
            },
        ),
        migrations.CreateModel(
            name='SkuOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babyusername', models.CharField(default='', max_length=20, verbose_name='产品中文名')),
                ('babyname', models.CharField(max_length=20, verbose_name='产品类别')),
                ('clientname', models.CharField(max_length=20, verbose_name='收件人')),
                ('mobile', models.CharField(max_length=15, verbose_name='手机号')),
                ('price', models.FloatField(max_length=10, verbose_name='金额')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(default='', max_length=30, verbose_name='地址')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('remark', models.CharField(default='', max_length=50, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('projectSkuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projectSku')),
            ],
            options={
                'verbose_name': '订单编号',
                'verbose_name_plural': '订单编号',
            },
        ),
        migrations.AddField(
            model_name='orderuser',
            name='orderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projectSku'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='orderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.orderUser'),
        ),
    ]
